DROP ALL OBJECTS;
DROP TABLE IF EXISTS PRICE;

CREATE SCHEMA SCHEME_PRICE;
SET SCHEMA SCHEME_PRICE;

CREATE TABLE PRICE
(
    BRAND_ID   INT         NOT NULL,
    START_DATE LONG        NOT NULL,
    END_DATE   LONG        NOT NULL,
    PRICE_LIST INT         NOT NULL,
    PRODUCT_ID BIGINT      NOT NULL,
    PRIORITY   INT         NOT NULL,
    PRICE      DECIMAL     NOT NULL,
    CURR       VARCHAR(25) NOT NULL
);

ALTER TABLE PRICE
    ADD PRIMARY KEY (BRAND_ID, START_DATE, END_DATE, PRODUCT_ID);